// Generated by CoffeeScript 1.3.3
(function() {

  ($(document)).ready(function() {
    var audio, button, flash;
    audio = document.getElementById('audio');
    button = $('button.bam');
    flash = $('.flash');
    button.bind('touchstart', function() {
      return button.attr(':active');
    });
    return button.bind('click touchend', function() {
      audio.currentTime = 0;
      audio.play();
      flash.show();
      return flash.fadeOut();
    });
  });

}).call(this);
